project:
  type: default

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
    code-fold: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"

jupyter: python3

execute:
  enabled: true
  echo: true
  warning: false
  message: false
